services:
  uptimekuma:
    image: louislam/uptime-kuma:2.5.3-slim-rootless
    container_name: uptimekuma
    labels:
      - wud.trigger.include=dockercompose.auto
      - wud.tag.include=^\d+\.\d+\.\d+-slim-rootless$
    ports:
      - 100.105.29.96:3002:3001
    volumes:
      - /home/erik/docker/uptimekuma/data:/app/data
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - uptimekuma-net

networks:
  uptimekuma-net:
    driver: bridge
